language: perl
perl:
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
  - "5.22"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libogg0 libvorbis0a libogg-dev libvorbis-dev libssl-dev
  - cpanm -n Devel::Cover::Report::Coveralls

script:
  perl Build.PL && ./Build build && cover -test +ignore Build.pm -report coveralls
